# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Question.create([{question: 'Ask Why'},
							{question: 'Pay attention to details'},
							{question: 'Enjoy taking care of people'},
							{question: 'Become bored with repetitive activity'},
							{question: 'Like complex problem solving'},
							{question: 'Value independence highly'},
							{question: 'Have manual dexterity'},
							{question: 'Need to see tangible results quickly'},
							{question: 'Be energetic / have a high energy level'},
							{question: 'Be self-confident'},
							{question: 'Value time-off'},
							{question: 'Need control over a situation'},
							{question: 'Enjoy research'},
							{question: 'Work with my mind'},
							{question: 'Appreciate variety'},
							{question: 'Be team player'},
							{question: 'Have a long attention span'},
							{question: 'Prefer a planned schedule'},
							{question: 'Be easy going'},
							{question: 'Rely on experience rather than theory'},
							{question: 'Make decisions'},
							{question: 'Be energized by people'},
							{question: 'Be comfortable doing the same activity repeatedly'},
							{question: 'Have interests outside of medicine'},
							{question: 'Have good observational skills'},
							{question: 'Be interested in people'},
							{question: 'Have good listening skills'},
							{question: 'Be adventurous / like challenges'},
							{question: 'Communicate well'},
							{question: 'Be a leader'},
							{question: 'Be able to do more than one thing at a time'},
							{question: 'Value a good income'},
							{question: 'Like to organize people'},
							{question: 'Like to coordinate patients & their families'},
							{question: 'Be content in knowing a little about a lot'},
							{question: "Enjoy being involved in patients' lives"},
							{question: 'Tolerate the unknown'},
							{question: 'Accept schedule disruption'},
							{question: 'Accept long term outcomes'},
							{question: 'Be a thinker rather than a doer'},
							{question: 'Be thorough and deliberate'},
							{question: 'Enjoy long term relationships with people'},
							{question: 'Be a good coordinator'},
							{question: 'Be willing to work long hours'},
							{question: 'Be uncomfortable with poorly defined problems'},
							{question: 'Like gadgets and enjoy technology'},
							{question: 'Be serious and determined than easy going'},
							{question: 'Value organization highly'},
							{question: 'Be an achiever'},
							{question: 'Have trouble refusing requests'},
							{question: 'Prefer treatable illness'},
							{question: 'Identify with role models'},
							{question: 'Be comfortable with their own mortality'},
							{question: 'Think logically'},
							{question: 'Be optimistic'},
							{question: 'Be able to handle defeat graciously'},
							{question: 'Value prestige'},
							{question: 'Be outgoing'},
							{question: 'Be persevering'},
							{question: 'Value feedback from others'},
							{question: 'Be objective'},
							{question: 'Be doers than talkers'},
							{question: 'Value job security'},
							{question: 'Find satisfaction in small gains'},
							{question: 'Have interest in the basic science of medicine'},
							{question: 'Be perfectionistic'},
							{question: 'Be scholarly'},
							{question: 'Adapt to changes easily'},
							{question: 'Be mathematically inclined'},
							{question: 'Be visually oriented'},
							{question: 'Value achievement'},
							{question: 'Be calm in a crisis'},
							{question: 'Be warm and sympathetic'},
							{question: 'Be tolerant of others'},
							{question: 'Enjoy teaching people'},
							{question: 'Like harmony'},
							{question: 'Enjoy being an expert'},
							{question: 'Look for possibilities'},
							{question: 'Seek approval'},
							{question: 'Be a self-starter'},
							{question: 'Be comfortable with short term patient relationships'},
							{question: 'Deal with problems straightforwardly with direct action'}])





